// Code generated by "cue exp gengotypes"; DO NOT EDIT.

package params

// #AppiumInput is the `appium` verb's plugin_input: the method name plus its
// method-exclusive modifiers.
type AppiumInput struct {
	// method — the appium method name (the former core #AppiumMethod enum; the
	// verb's PRIMARY input field, so `appium: status` desugars to {method: "status"}).
	Method string `yaml:"method,omitempty" json:"method"`

	// caps — the W3C capabilities JSON (session-create; @path reads a file).
	Caps string `yaml:"caps,omitempty" json:"caps,omitempty"`

	// session — an explicit session id overriding the persisted session file.
	Session string `yaml:"session,omitempty" json:"session,omitempty"`

	// strategy / selector — the element locator (find/click/send-keys/…).
	Strategy string `yaml:"strategy,omitempty" json:"strategy,omitempty"`

	Selector string `yaml:"selector,omitempty" json:"selector,omitempty"`

	// text — the keys to send (send-keys).
	Text string `yaml:"text,omitempty" json:"text,omitempty"`

	// attribute — the element attribute name (get-attribute).
	Attribute string `yaml:"attribute,omitempty" json:"attribute,omitempty"`

	// apk — HOST path of the APK to stage + install (install-app); resolved to an
	// absolute candy-anchored path by the host before marshaling.
	Apk string `yaml:"apk,omitempty" json:"apk,omitempty"`

	// app_id — the application package id (app-activate/terminate/remove/…).
	AppId string `yaml:"app_id,omitempty" json:"app_id,omitempty"`

	// activity — the start-activity intent (`pkg/.activity`).
	Activity string `yaml:"activity,omitempty" json:"activity,omitempty"`

	// keycode — the Android keycode (key-press).
	Keycode int `yaml:"keycode,omitempty" json:"keycode,omitempty"`

	// params — free-form JSON args merged into the mobile: command
	// (gestures/app/key/device groups), or the scalar value for
	// device-set-orientation / device-set-clipboard / device-context.
	Params string `yaml:"params,omitempty" json:"params,omitempty"`

	// x / y — coordinate target for a gesture with no selector.
	X int `yaml:"x,omitempty" json:"x,omitempty"`

	Y int `yaml:"y,omitempty" json:"y,omitempty"`

	// direction / percent — swipe/scroll/fling geometry.
	Direction string `yaml:"direction,omitempty" json:"direction,omitempty"`

	Percent string `yaml:"percent,omitempty" json:"percent,omitempty"`

	// expression — the execute method's script (`mobile: <cmd>` or JS).
	Expression string `yaml:"expression,omitempty" json:"expression,omitempty"`

	// http_method / path / request_body — the raw escape hatch: the W3C HTTP verb
	// (http_method — renamed from the former shared #Op `method`), the
	// /session/<id>-relative path, and the JSON body ({element} substitution when
	// selector is set; execute reads request_body too).
	HTTPMethod string `yaml:"http_method,omitempty" json:"http_method,omitempty"`

	Path string `yaml:"path,omitempty" json:"path,omitempty"`

	RequestBody string `yaml:"request_body,omitempty" json:"request_body,omitempty"`

	// artifact + validators — screenshot's PNG output path and the post-run
	// artifact-reality assertions (sdk.RunArtifactValidators reads them off the input).
	Artifact string `yaml:"artifact,omitempty" json:"artifact,omitempty"`

	ArtifactMinBytes int `yaml:"artifact_min_bytes,omitempty" json:"artifact_min_bytes,omitempty"`

	ArtifactMinDimensions string `yaml:"artifact_min_dimensions,omitempty" json:"artifact_min_dimensions,omitempty"`

	ArtifactNotUniform bool `yaml:"artifact_not_uniform,omitempty" json:"artifact_not_uniform,omitempty"`

	ArtifactMinCastEvents int `yaml:"artifact_min_cast_events,omitempty" json:"artifact_min_cast_events,omitempty"`
}
